name: Test1
on: 
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/workflows/**'
  pull_request_target:
    branches:
      - 'main'
    paths:
      - '.github/workflows/**'
      
jobs:
  job_print_env_vars:
    runs-on: ubuntu-latest
    steps:
      - name: Print some GH vars
        run: |
          echo github.event_name: ${{ github.event_name }}
          echo github.ref: ${{ github.ref }}
          echo github.ref_name: ${{ github.ref_name }}
          echo github.head_ref: ${{ github.head_ref }}
          echo github.base_ref: ${{ github.base_ref }}

      - name: List ubuntu env vars 
        run: env

      - name: List github env vars 
        run: echo '${{ toJSON(github) }}'
