name: Test PR
on: 
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/workflows/**'

    
jobs:
  job_print_env_vars:
    runs-on: ubuntu-latest
    steps:
      - name: List env vars on ubuntu
        run: env

      - name: List context vars
        run: echo '${{ toJSON(github) }}'

      - name: Print GH vars
        run: |
          echo github.event_name: ${{ github.event_name }}
          echo github.ref: ${{ github.ref }}
          echo github.ref_name: ${{ github.ref_name }}
          echo github.head_ref: ${{ github.head_ref }}
          echo github.base_ref: ${{ github.base_ref }}